bl_info = {
    "name": "MOVE AI FBX IMPORTER",
    "author": "MOVE AI FBX IMPORTER",
    "version": (1, 0),
    "blender": (2, 80, 0),
    "location": "View3D > Tools",
    "description": "Import your motion captures generated by Move AI",
    "category": "3D View > Animation",
}
import bpy
from .ui import MOVEAI_IMPORTER_PT_download_panel
from .operators import MOVEAI_IMPORTER_OT_download_anim
from .properties import MoveaiImporterProperties

bl_classes = [MOVEAI_IMPORTER_PT_download_panel,
              MOVEAI_IMPORTER_OT_download_anim, MoveaiImporterProperties]


def register() -> None:
    for bl_class in bl_classes:
        bpy.utils.register_class(bl_class)

    bpy.types.Scene.moveai = bpy.props.PointerProperty(
        type=MoveaiImporterProperties)


def unregister() -> None:
    del bpy.types.Scene.moveai

    for bl_class in bl_classes:
        bpy.utils.unregister_class(bl_class)


if __name__ == "__main__":
    register()
